# Site settings
title: Redmaner
copyright: Copyright (c) 2014, all rights reserved
description: > # this means to ignore newlines until "baseurl:"
  Redmaner, known for Android projects such as GingerReal and MIUI.
  Now a simple blogger, developer and designer. 
  Continue if you like technology and (digital) laws just like I do.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://redmaner.github.io" # the base hostname & protocol for your site
twitter_username: redmaner_
github_username:  redmaner

# Build settings
markdown: kramdown
